server:
  port: 8800

spring:
  application:
    name: carbon
    #mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carbon?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: admin
  data:
    #redis
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      password:
      jedis:
        pool:
          max-active: 20 #最大连接数
          max-wait: -1  #最大阻塞等待时间(负数表示没有限制)
          max-idle: 5 #最大空闲
          min-idle: 0 #最小空闲
  # 配置rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    #确认消息已发送到交换机(Exchange) 成功失败都会触发(指消费者端的绑定)
    publisher-confirm-type: simple
    #确认消息已发送到队列(Queue) 失败触发(指消费者端的绑定)
    publisher-returns: true

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: assign_id
      # 表名是否使用驼峰转下划线命名,只对表名生效。 默认true
      table-underline: true
  configuration:
    cache-enabled: true
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
#log4j2
logging:
  config: classpath:log4j2.xml



